<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{

	protected $guarded = [];

	protected  $casts = [
	    'completed' => 'boolean'
    ];


	// updates parent records
	protected $touches = ['project'];

    /**
     *
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }


    public function complete()
    {

        $this->update(['completed' => true]);

        $this->project->recordActivity('completed_task');

    }

    public function incomplete()
    {

        $this->update(['completed' => false]);

        $this->project->recordActivity('incompleted_task');

    }


    public function project()
	{

		return $this->belongsTo(Project::class);

	}

	public function path()
	{

		return "/projects/{$this->project->id}/tasks/{$this->id}";

	}

}

